export const similars = [
  {
    id: 1,
    url: "https://picsum.photos/200/300",
    first_name: "asdf",
    last_name: "asdf",
    followers: "102k",
  },
  {
    id: 2,
    url: "https://picsum.photos/200/300",
    first_name: "wer",
    last_name: "wer",
    followers: "102k",
  },
  {
    id: 3,
    url: "https://picsum.photos/200/300",
    first_name: "sdfsd",
    last_name: "sdfsdf",
    followers: "102k",
  },
  {
    id: 4,
    url: "https://picsum.photos/200/300",
    first_name: "retert",
    last_name: "ertert",
    followers: "102k",
  },
  {
    id: 5,
    url: "https://picsum.photos/200/300",
    first_name: "ertert",
    last_name: "erter",
    followers: "102k",
  },
  {
    id: 6,
    url: "https://picsum.photos/200/300",
    first_name: "gfh",
    last_name: "fghfgh",
    followers: "102k",
  },
  {
    id: 7,
    url: "https://picsum.photos/200/300",
    first_name: "hghj",
    last_name: "ghjh",
    followers: "102k",
  },
  {
    id: 8,
    url: "https://picsum.photos/200/300",
    first_name: "ghjh",
    last_name: "ghjgh",
    followers: "102k",
  },
  {
    id: 9,
    url: "https://picsum.photos/200/300",
    first_name: "retert",
    last_name: "erter",
    followers: "102k",
  },
];
